name: "AIM"
fullName: "AIM Robotics"
acronymExpansion: "Autonomous Intelligent Machines"
motto: "Pushing the State-Of-The-Art"
university: "University of Calgary"
location: "Calgary, Alberta"
locationShort: "CALGARY, AB"
